# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  difit = {
    pname = "difit";
    version = "v5.0.8";
    src = fetchFromGitHub {
      owner = "yoshiko-pg";
      repo = "difit";
      rev = "v5.0.8";
      fetchSubmodules = false;
      sha256 = "sha256-AT2dUT14+yfMLxcJdJC/CI28RfyElsoa97vxUIMjUo0=";
    };
  };
  difit-npm = {
    pname = "difit-npm";
    version = "5.0.8";
    src = fetchurl {
      url = "https://registry.npmjs.org/difit/-/difit-5.0.8.tgz";
      sha256 = "sha256-RGXJlgKComDU4xcxZWkYD84kMM5fR1oM1XsHhpyCvA0=";
    };
  };
}
